### ISSUE TITLE
Options not shown in --help

### ISSUE THREAD

**Issue by PhilippSoehnlein** [artefact-group/yeoman-option-or-prompt#1]
I just discovered yeoman-option-or-prompt and really like the idea. 
But it would be nice if the options would be shown when the generator is called with `--help`. Any chance?

**Comment by sambaker** [comment]
@PhilippSoehnlein that's up to the author of the generator. This project just provides a function that allows generators to use options to override prompts. The generator author should decide whether to publish those options as part of the generator's interface. See http://yeoman.io/authoring/user-interactions.html for details on how to declare options. I assume that declaring options in the constructor is what allows yo to show them with `yo <generator> --help`.

If you are using yeoman-option-or-prompt, you can just declare options in your generator's constructor that match the names of the prompts that you're passing to optionOrPrompt.
