### ISSUE TITLE
v2.0.1 is not published

### ISSUE THREAD

**Issue by uladkasach** [artefact-group/yeoman-option-or-prompt#13]
v2.0.0 has a bug that v2.0.1 does not. Unfortunately, v2.0.1 is not published. Please publish this package

**Comment by funwhilelost** [comment]
@uladkasach - is v2.0.1 the tip of master in this fork or is there another fork out there with 2.0.1?

**Comment by funwhilelost** [comment]
@sambaker - I've pushed up a version tag for v2.0.1 with the contributions from the community.  Would you be able to `git pull` and `npm publish` this?

Also - it'd be great to add me as an npm owner so I can publish to npm: `npm owner add funwhilelost yeoman-option-or-prompt`

**Comment by uladkasach** [comment]
@funwhilelost The master branch `package.json` states v2.0.1 is the tip of master for this fork.

**Comment by sambaker** [comment]
v2.0.1 has been published, @funwhilelost thanks for your help with this!
